spring:
  application:
    name: sudfe-forum-pro-gateway
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:config.yml,classpath:limiter.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: sdufe-forum-pro-auth
          uri: lb://sdufe-forum-pro-auth
          predicates:
            - Path=/auth/**,/token/**
        - id: sdufe-forum-pro-app
          uri: lb://sdufe-forum-pro-app
          predicates:
            - Path=/user/**,/article/**
server:
  port: 8090
